<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Adherent extends \App\Entity\Adherent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'idcarte', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'iddistri', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'datecreation', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'ordrePassage', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'passages'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'idcarte', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'iddistri', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'datecreation', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'ordrePassage', '' . "\0" . 'App\\Entity\\Adherent' . "\0" . 'passages'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Adherent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPassages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassages', []);

        return parent::getPassages();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcarte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcarte', []);

        return parent::getIdcarte();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcarte($idcarte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcarte', [$idcarte]);

        return parent::setIdcarte($idcarte);
    }

    /**
     * {@inheritDoc}
     */
    public function getIddistri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIddistri', []);

        return parent::getIddistri();
    }

    /**
     * {@inheritDoc}
     */
    public function setIddistri($iddistri)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIddistri', [$iddistri]);

        return parent::setIddistri($iddistri);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', []);

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', [$datecreation]);

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPassage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPassage', []);

        return parent::getNbPassage();
    }

    /**
     * {@inheritDoc}
     */
    public function setordrePassage($ordrePassage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setordrePassage', [$ordrePassage]);

        return parent::setordrePassage($ordrePassage);
    }

    /**
     * {@inheritDoc}
     */
    public function getordrePassage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getordrePassage', []);

        return parent::getordrePassage();
    }

    /**
     * {@inheritDoc}
     */
    public function isCheckPassage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCheckPassage', []);

        return parent::isCheckPassage();
    }

}
