<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.menu_builder' shared autowired service.

include_once $this->targetDirs[2].'/src/Menu/MenuBuilder.php';

return $this->privates['app.menu_builder'] = new \App\Menu\MenuBuilder(($this->services['knp_menu.factory'] ?? $this->load(__DIR__.'/getKnpMenu_FactoryService.php')));
