<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH32a07x\srcDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH32a07x/srcDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerH32a07x.legacy');

    return;
}

if (!\class_exists(srcDebugProjectContainer::class, false)) {
    \class_alias(\ContainerH32a07x\srcDebugProjectContainer::class, srcDebugProjectContainer::class, false);
}

return new \ContainerH32a07x\srcDebugProjectContainer(array(
    'container.build_hash' => 'H32a07x',
    'container.build_id' => 'ce4a1009',
    'container.build_time' => 1517223400,
));
