<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXeWeEQc\srcTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXeWeEQc/srcTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXeWeEQc.legacy');

    return;
}

if (!\class_exists(srcTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXeWeEQc\srcTestDebugProjectContainer::class, srcTestDebugProjectContainer::class, false);
}

return new \ContainerXeWeEQc\srcTestDebugProjectContainer(array(
    'container.build_hash' => 'XeWeEQc',
    'container.build_id' => '63a0a1d6',
    'container.build_time' => 1517222733,
));
